spring:
  h2.console:
    enabled: false
  datasource:
    url: jdbc:h2:file:./user-managment
  jpa.hibernate:
    ddl-auto: update

auth:
  jwt:
    expirationDays: 30
    secret: ${USER_SECRET}
    issuer: user-managment-service
